#!/usr/bin/env python3
"""
Σ₀ V12 — Shorts Visual Research Engine (Phase 1: Video Observer).

Pipeline: video -> ffmpeg frame/motion -> audio spikes -> scene cuts ->
facecam/HUD detection (safe-zone-v2.js) -> opening hook strength -> JSON.
Reuses the project's existing, tested Node detectors via
_visual_research_helper.js rather than reimplementing them in Python.

Scope (read before pointing this at a new source):
  - Lantern's own first-party rendered exports: unlimited, no restriction.
  - Third-party videos: small curated sample ONLY (same ~28-40-video
    convention as research_loop_calibration.py), never bulk/at-scale. This
    script does not download anything itself — callers pass an already
    -downloaded local path, and are responsible for deleting it after.
  - OCR subtitle detection (subtitle_style, caption_density for
    third-party clips) is NOT implemented — no OCR engine is installed in
    this environment. Those fields are honestly "insufficient_data", never
    guessed. zoom_frequency has no detector built yet either (no
    zoom/crop-change signal exists in the codebase) — also
    "insufficient_data".

Output: data/shorts_research/<video_id>.json
"""

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HELPER = ROOT / "scripts" / "_visual_research_helper.js"
OUT_DIR = ROOT / "data" / "shorts_research"

INSUFFICIENT = "insufficient_data"


def run_node_helper(video_path: Path) -> dict:
    proc = subprocess.run(
        ["node", str(HELPER), str(video_path)],
        capture_output=True, text=True, timeout=180,
    )
    try:
        return json.loads(proc.stdout.strip())
    except json.JSONDecodeError:
        return {"status": "unavailable", "reason": f"helper produced no valid JSON: {proc.stderr[-300:]}"}


def caption_density_from_lantern_captions(captions: list, duration: float) -> float:
    """Real caption_density for Lantern's OWN exports (captions are known
    exactly — generated by caption-engine.js — not OCR-guessed)."""
    if not captions or not duration:
        return 0.0
    return round(len(captions) / (duration / 60.0), 3)  # captions per minute


def build_record(video_id: str, video_path: Path, metadata: dict | None = None,
                  lantern_captions: list | None = None) -> dict:
    metadata = metadata or {}
    helper_result = run_node_helper(video_path)

    if helper_result.get("status") != "ok":
        return {
            "video_id": video_id,
            "status": "unavailable",
            "reason": helper_result.get("reason", "helper failed"),
        }

    duration = helper_result["durationSec"]
    motion_curve = helper_result["motionCurve"]

    # engagement: real if metadata supplies view/like/comment counts (third
    # -party calibration clips); insufficient_data for Lantern's own
    # not-yet-published exports — never guessed either way.
    views = metadata.get("views")
    likes = metadata.get("likes")
    comments = metadata.get("comments")
    if isinstance(views, (int, float)) and views > 0:
        engagement = round(((likes or 0) + (comments or 0)) / views, 6)
    else:
        engagement = INSUFFICIENT

    if lantern_captions is not None:
        caption_density = caption_density_from_lantern_captions(lantern_captions, duration)
        subtitle_style = "lantern_generated"
    else:
        caption_density = INSUFFICIENT  # would require OCR on third-party source video
        subtitle_style = INSUFFICIENT

    record = {
        "video_id": video_id,
        "status": "ok",
        "fps": helper_result["fps"],
        "duration_sec": duration,
        "average_cut_length": helper_result["averageCutLength"],
        "hook_duration": helper_result["openingHookStrength"],  # see honesty note below
        "zoom_frequency": INSUFFICIENT,  # no zoom/crop-change detector exists yet
        "subtitle_style": subtitle_style,
        "caption_density": caption_density,
        "motion_curve": motion_curve,
        "facecam_position": helper_result["facecamPosition"],
        "hud_position": helper_result["hudPosition"],
        "emotional_peaks": helper_result["audioSpikeTimestamps"],  # proxy: audio-spike timestamps, not a real emotion model
        "engagement": engagement,
        "source": metadata.get("source", "lantern_own_export" if lantern_captions is not None else "third_party_calibration_sample"),
        "honesty_note": (
            "hook_duration here is detectOpeningHookStrength()'s 0-1 score, not "
            "a literal seconds value (see research/hour_12.md re: that detector's "
            "known saturation issue, not yet recalibrated). emotional_peaks is an "
            "audio-spike-timestamp proxy, not a trained emotion-detection signal. "
            "zoom_frequency/subtitle_style/caption_density for third-party clips "
            "are insufficient_data, never guessed."
        ),
    }
    return record


def main():
    if len(sys.argv) < 2:
        print("usage: shorts_visual_research.py <video_path> [video_id]")
        return
    video_path = Path(sys.argv[1])
    video_id = sys.argv[2] if len(sys.argv) > 2 else video_path.stem

    record = build_record(video_id, video_path)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out_file = OUT_DIR / f"{video_id}.json"
    out_file.write_text(json.dumps(record, indent=2), encoding="utf-8")
    print(json.dumps(record, indent=2))


if __name__ == "__main__":
    main()
